name: CMake Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            preset: ninja-release
            cc: gcc
            cxx: g++

          - os: windows-latest
            preset: msvc-release

    steps:
      - uses: actions/checkout@v4

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@f176ccd3f28bda569c43aae4894f06b2435a3375
        with:
          cmakeVersion: latestrc
          ninjaVersion: latest

      - name: Configure
        if: runner.os == 'Linux'
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: cmake --preset ${{ matrix.preset }}

      - name: Configure
        if: runner.os == 'Windows'
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}