name: CMake Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            preset: ninja-release-clang19

          - os: windows-latest
            preset: msvc-release

    steps:
      - uses: actions/checkout@v4

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@f176ccd3f28bda569c43aae4894f06b2435a3375
        with:
          cmakeVersion: latestrc
          ninjaVersion: latest

      - name: Install Clang 19
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-19 clang-tools-19 lld-19

      - name: Show compiler tools
        if: runner.os == 'Linux'
        run: |
          clang-19 --version
          clang++-19 --version
          clang-scan-deps-19 --version
          which clang-scan-deps-19

      - name: Configure
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}